_format_version: "2.1"

services:
  - name: auth
    url: http://auth:9999
    routes:
      - name: auth-route
        paths:
          - /auth/v1
        strip_path: true

  - name: postgrest
    url: http://postgrest:3000
    routes:
      - name: postgrest-route
        paths:
          - /rest/v1
        strip_path: true

  - name: storage-api
    url: http://storage-api:54321
    routes:
      - name: storage-route
        paths:
          - /storage/v1
        strip_path: true

  - name: realtime
    url: http://realtime:4000/socket
    routes:
      - name: realtime-route
        paths:
          - /realtime
        strip_path: false

  - name: health
    url: http://postgrest:3000
    routes:
      - name: root
        paths:
          - /